1. нужно скандировать матрицу 5*5, которая состоит из различных чисел. скандировать значит получить доступ к элементам матрицы последовательно

In [12]:
import numpy as np
a = np.arange(25).reshape((5,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


2. какие принципи ООП ты знаешь

Ответ: наследование, полиморфизм и инкапсуляция (+абстракция)

3. Какие магические методы в Пайтон знаешь?
Ответ: len,арифметические операции, getiter, getater,str, repr

4. Чем отличается str, repr?

5. Зачем нужен self...

6. Зачем метод dir для обьектов

7. В чем отличие методов apply applymap Pandas?

8. Продолжи: try except ....

9. В чем разница между листом и кортежем?

10. Зачем нужен yield вместо return?

11. В чем различие loc и iloc?

атрибут loc позволяет выполнить индексацию и срезы с использованием явного индекса.
атрибут iloc позволяет выполнить срезы и индексацию с использование неявного индекса в стиле языка пайтон

12. Что делает transform в dataframe

13. В чем разница между pivot и pivottable в пандас

14. Написать программу которая на вход принимает строку и разворачивает ее

In [13]:
def reverse(str):
    return bin(str[::-1])

print(reverse('tania'))

TypeError: 'str' object cannot be interpreted as an integer

15. Что такое бинарный поиск - это алгоритм. На входе он получает отсортированный массив. Если искомый элемент находится в списке, то возвращается индекс искомого элемента. в противном случае возвращает null.
Допустим мне нужно найти элемент из 100. Сначала мы отсекаем половину, остается искать среди 50. Затем еще половину, 25, еще половину, 13, еще половину, 7, еще половину, 4, еще половину, 2 и наконец 1. То есть найти элемент из 100 мы можем найти не более чем за 7 раз. 
В случае с n элементами, бинарный поиск выполняется за не более чем log_2(n) раз

следующий код применяется только к отсортированному массиву

In [31]:
def binary_search(array,el):
    low = 0
    high = len(array)-1
    while low <= high:
        mid = (low + high)//2
        guess = array[mid]
        if guess == el:
            return mid
        if guess > el:
            high = mid - 1
        else:
            low = mid + 1
    return None

my_array = [1,3,5,7,9,10]
print(binary_search(my_array,11))

None


16. O большое описывает насколько быстро работает алгоритм. Измеряется в темпах роста кол-ва операций.
Время выполнения программы будет линейным если кол-во максимальных циклов выполнения совпадает с кол-вом элементов входящего массива. Например, при простом поиске элемента из массива макс кол-во попыток совпадает с кол-вом элементов массива - тогда это линейное время выполнения O(n)
В случае с бинарным поиском максимальное кол-во попыток равно лог по основанию 2 от n. Тогда время выполнения O(log_2(n))


5 основных разновидностей О большого:
1) О(n)
2) O(log(n))
3) O(nlog(n))
4) O(n!)
5) O(n^2)
