1. нужно скандировать матрицу 5*5, которая состоит из различных чисел. скандировать значит получить доступ к элементам матрицы последовательно

In [12]:
import numpy as np
a = np.arange(25).reshape((5,5))
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


2. какие принципи ООП ты знаешь

Ответ: наследование, полиморфизм и инкапсуляция (+абстракция)

3. Какие магические методы в Пайтон знаешь?
Ответ: len,арифметические операции, getiter, getater,str, repr

4. Чем отличается str, repr?

5. Зачем нужен self...

6. Зачем метод dir для обьектов

7. В чем отличие методов apply applymap Pandas?

8. Продолжи: try except ....

9. В чем разница между листом и кортежем?

10. Зачем нужен yield вместо return?

11. В чем различие loc и iloc?

атрибут loc позволяет выполнить индексацию и срезы с использованием явного индекса.
атрибут iloc позволяет выполнить срезы и индексацию с использование неявного индекса в стиле языка пайтон

12. Что делает transform в dataframe

13. В чем разница между pivot и pivottable в пандас

14. Написать программу которая на вход принимает строку и разворачивает ее

In [2]:
def reverse(str):
    return str[::-1]

print(reverse('tania'))

ainat


15. Что такое бинарный поиск - это алгоритм. На входе он получает отсортированный массив. Если искомый элемент находится в списке, то возвращается индекс искомого элемента. в противном случае возвращает null.
Допустим мне нужно найти элемент из 100. Сначала мы отсекаем половину, остается искать среди 50. Затем еще половину, 25, еще половину, 13, еще половину, 7, еще половину, 4, еще половину, 2 и наконец 1. То есть найти элемент из 100 мы можем найти не более чем за 7 раз. 
В случае с n элементами, бинарный поиск выполняется за не более чем log_2(n) раз

следующий код применяется только к отсортированному массиву

In [3]:
def binary_search(array,el):
    low = 0
    high = len(array)-1
    while low <= high:
        mid = (low + high)//2
        guess = array[mid]
        if guess == el:
            return mid
        if guess > el:
            high = mid - 1
        else:
            low = mid + 1
    return None

my_array = [1,3,5,7,9,10]
print(binary_search(my_array,11))

None


16. O большое описывает насколько быстро работает алгоритм. Измеряется в темпах роста кол-ва операций.
Время выполнения программы будет линейным если кол-во максимальных циклов выполнения совпадает с кол-вом элементов входящего массива. Например, при простом поиске элемента из массива макс кол-во попыток совпадает с кол-вом элементов массива - тогда это линейное время выполнения O(n)
В случае с бинарным поиском максимальное кол-во попыток равно лог по основанию 2 от n. Тогда время выполнения O(log_2(n))


5 основных разновидностей О большого:
1) О(n)
2) O(log(n))
3) O(nlog(n))
4) O(n!)
5) O(n^2)


17. напишем функцию для поиска наименьшего элемента массива

In [4]:
def find_smallest(list):
    smallest_el = list[0]
    smallest_index = 0
    for el in range(1,len(list)):
        if list[el]<smallest_el:
            smallest_index = el
            smallest_el = list[el]
    return smallest_el


find_smallest([3,45,6,7,8,10,-4,89,-2])

-4

18. СОРТИРОВКА ВЫБОРОМ (темп выполнения O(n^2))
На основе этой функции написать функцию сортировки выбором(selection sort)

In [5]:
def selection_sort(arr):
    newArr=[]
    for i in range(len(arr)):
        smallest_el = find_smallest(arr)
        newArr.append(smallest_el)
        arr.remove(smallest_el)
    return newArr

selection_sort([3,45,6,7,8,10,-4,89,-2])

[-4, -2, 3, 6, 7, 8, 10, 45, 89]

19. Псевдокод - это высокоуровневое описание решаемой задачи

20. Рекурсия - это когда функция вызывает саму себя. В каждой рекурсивной функции должно быть 2 случая (базовый и рекурсивный). Все вызовы функций сохраняются в стеке вызовов.

21. Поиск ключа в коробке с коробками. Алгоритм 1:
сначала мы берем все коробку с коробками
пока коробки еще есть:
для каждой коробки в этой куче:
если предмет внутри коробки оказался коробкой - возвращаем в кучу
если предмет оказался ключом мы нашли ключ

In [6]:
def look_for_key(main_box):
    pile = main_box.make_a_pile_to_look_through()
    while pile is not empty:
        box=pile.grab_a_box()
        for item in box:
            if item.is_a_box():
                pile.append(item)
            elif item.is_a_key():
                print("found the key")

Второй способ (основан на рекурсии):
сначала мы берем коробку с коробками и проверяем каждый элемент в нем:
если элемент оказался коробкой, повторяем пунукт 1
иначе мы нашли ключ

In [ ]:
def look_for_key(box):
    for item in box:
        if item.is_a_box():
            look_for_key(item)
        elif item.is_a_key():
            print("found the key")

22. Алгоритм Эвклида - подход к решению задач "Разделяй и властвуй"
1. сначала определяем базовый случай
2. придумываем как свести задачу к базовому случаю.
Например нужно покрыть прямоугольник максимально большими квадратами. 
Базовый случай когда длина кратна ширине
откладывае ширину по длине пока есть место. дальше проделываем эту же процедуру в оставшимся прямоугольником. пока не получим базовый случай

23. Как посчитать сумму чисел в массиве используя рекурсию
базовый случай это пустой список. сумма равна нулю.
если список пуст то сумма равна 0
в противном случае: к первому числу списка прибавлять сумму оставшихся


In [ ]:
def sum(arr):
    if arr == []:
        return 0
    else:
        return arr[0]+sum(arr[1:])
    
sum([2,4,1])

7

24. напишите рекурсивную функцию для подсчета элементов в списке

In [ ]:
def count_el()


25. Какие методы предотвращения переобучения (регуляризации) для нейронных сетей вы знаете? Как они работают? Куда вставлять batch normalization? 


26. — Чем отличается нейронная сеть с одним выходом и сигмоидальной функции активации и такая же нейронная сеть, но с двумя выходами и softmax? 

27. — Представим, что у нас есть многослойная полносвязанная сеть с нелинейной функцией активации. Что будет с нейронной сетью, если мы уберём нелинейность?


28. — Для чего используют global pooling? 


29. — Как оценивают качество в задачах object detection? 


30. — Какие архитектуры нейронных сетей для семантической сегментации вы знаете?

31. — Как и зачем использовать transfer learning?

32. — Как правильно тестировать качество моделей в работе с временными рядами? 

33. — Что мы должны делать с сезонностью в данных? 

34. — Как искать аномалии во временных рядах? 

35. — Что лежит в основе моделирования тематик? Как работает этот алгоритм? Как вы выберете число тематик, которые будут обучаться этим алгоритмом?

36. — У вас есть текст отзывов и рейтинг, пользователи используют 5-балльную шкалу. Как бы вы построили систему, которая сможет предсказывать оценку по тексту отзыва? Как оценивать качество этой системы? 


37. БЫСТРАЯ СОРТИРОВКА - метод сортировке основан на рекурсии. Темп выполнения (в худшем случае O(n^2) в среднем O(nlogn))
Допустим у меня есть массив из 5 элементов. Я выбираю опорный элемент и разделяю массив на два подмассива (первый: все элементы меньше опорного и второй: все элементы больше опорного). и к каждому из подмассивова также применяю быструю сортировку.
в качестве опорного элемента лучше выбирать случайный элемент это приведет к тому что быстрая сортировка завершится за O(nlogn)

38. Написать функцию для быстрой сортировки


In [9]:
def quicksort(array):
    if len(array)<2:
        return array
    else:
        pivot = array[0]
        less = [i for i in array[1:] if i <= pivot]
        greater = [i for i in array[1:] if i > pivot]
    return quicksort(less) + [pivot] + quicksort(greater)
print(quicksort([10,5,2,3]))


[2, 3, 5, 10]


39. СОРТИРОВКА СЛИЯНИЕМ средний темп выполнения O(nlogn)
суть: сначала разбиваем множества на подмножества до тех пор пока не получим подмножества выставленными в порядке возрастания.
затем начинаем сливания. Например 3,9,-2,4,5,10,12 -> (3,9), (-2,4), (5,10), 12 -> (-2,3,4,9), (5,10,12) -> (-2,3,4,5,9,10,12)

In [ ]:
40. Написать функцию сортировки слиянием

In [24]:
def merge_list(a,b):
    c=[]
    N=len(a)
    M=len(b)
    i = 0
    j = 0
    while (i < N) and (j<M):
        if a[i] <= b[j]:
            c.append(a[i])
            i+=1
        else:
            c.append(b[j])
            j+=1
    c += a[i:] + b[j:]
    return c

In [26]:
def split_and_merge_list(a):
    N1 = len(a)//2
    a1 = a[:N1]
    a2 = a[N1:]
    if len(a1)>1:
        a1 = split_and_merge_list(a1)
    if len(a2)>1:
        a2 = split_and_merge_list(a2)
    return merge_list(a1,a2)

a = [2,3,-5,6,7]
print(split_and_merge_list(a))

[-5, 2, 3, 6, 7]


41. ХЕШ-таблицы (словарь). Это функция которая получает на вход строку и возвращает число (индекс) ячейки памяти в которой хранится эта строка. Хороши для моделирования отношения между обьектами, устранения дубликатов. В идеале хеш-функция должна распределять ключи равномерно по всему хешу.

Хеширование - преобразоваие данных любой длины в данные фиксированной длины

42. Функция для проверки дубликата в списке голосовавших

In [ ]:
def check_ducblicat(name):
    voted = {}
    if voted.get(name):
        print('Kick them out!')
    else:
        voted[name]=True
        print('let them vote')
    

43. Кеширование - механизм хранения данных для ускорения работы сервера. Кешируемые данные хранятся в хеше.

44. КОЛЛИЗИЦИ

45. ГРАФ это набор связей

46. ПОИСК В ШИРИНУ  это алгоритм, позволящий перебрать при котором поиск рано или поздно пройдет по всей сети. Поиск в шириу позволяет ответить на 2 вопроса: 1) сущетсвует ли путь от узла А к узлу В? 2)как выглядит кратчайший путь от узла А к узлу Б?

47. FIFO (first in, first out) - списки и LIFO(last in first out) - стек. Это структуры данных

48. РЕАЛИЗАЦИЯ ГРАФА (чтобы показать связь я-друщья на фейсбук используем хеш таблица)

In [4]:
graph={}
graph['Tania'] = ['alice','bob','claire']
graph['bob']=['anuj','peggy']
graph['alice']=['peggy']
graph['claire']=['thom','jonny']
graph['anuj']=[]
graph['peggy']=[]
graph['thom']=[]
graph['jonny']=[]

49. НАПРАВЛЕННЫЕ И НЕНАПРАВЛЕННЫЕ ГРАФЫ. (направленный - отношение дейтсвуют только в одну сторону, неправлаенныей - в обе стороны)
ДЕРЕВО - это граф в котором нет ребе, указавыющих в братном направлении.

50. РЕАЛИЗАЦИЯ АЛГОРИТМА ПОИСКА В ШИРИНУ.

In [5]:
def person_is_seller(name):
    return name[-1] == 'm'

In [10]:
from collections import deque
def search(name):
    search_queue = deque(name)
    search_queue +=graph['name']
    searched = []
    while search_queue:
        person = search_queue.popleft()
        if not person in searched:
            if person_is_seller(person):
                print(f"{person} is a mango seller!")
            return True
        else:
            search_queue += graph[person]
            searched.append(person)
        return False



51. Алгоритм Дейкстры. Предположим у нас есть граф и нам нужно найти самый быстрый способ дойти из одной точки в другую. 
Граф который у нас есть взвешенный (значит что каждое ребро имеет свои веса). Нужно выбрать путь который даст наименьший вес в результате при проходе из пункта А в пункт В. Применяется только к графу с неотрицательными весами ребер


52. РЕАЛИЗАЦИЯ Алгоритма Дейкстры

53. NP полные задачи. Это Невозможые задачи, для которых нет алгоритма для их быстрого решения

54. ЖАДНЫЕ АЛГОРИТМЫ - это те, на каждом шаге которого выбирается оптимальный вариант (локально-оптимальное решение)

55. КОЛИЧЕСТВО ВСЕХ ПОДМНОЖЕСТВО ДАНОГО МНОЖЕТСВА равна 2^n. (c(n,0) + c(n,1) + c(n,2) + c(n,3) + ... +c(n,n) = 2^n)

56. РЕАЛИЗАЦИЯ ЖАДНОГО АЛГОРИТМА в задаче о покрытие множества. 
Постановка задачи: есть список станций для радиовещания у каждого из которых есть список штатов которые эта станция покрывает.
найти наилучшее покрытие этими станциями всех штатов.
1) сначала находим станцию которая покрывает наибольшее количество штатов
2) среди оставшихся выбираем станцию которая покрывает наибольшее кол-во станций
3) делаем это до тех пор пока все штаты не будут покрыты.


In [2]:
states_needed = set(["mt", "wa", "or", "id", "nv", "ut", "ca", "az"])
stations = {}
stations["kone"] = set(["id", "nv", "ut"])
stations["ktwo"] = set(["wa", "id", "mt"])
stations["kthree"] = set(["or", "nv", "ca"])
stations["kfour"] = set(["nv", "ut"])
stations["kfive"] = set(["ca", "az"])
final_stations = set()
while states_needed:
    best_station = None
    states_covered = set()
    for station, states_for_station in stations.items():
        covered = states_needed & states_for_station
        if len(covered) > len(states_covered):
            best_station = station
            states_covered = covered
    final_stations.add(best_station)
    states_needed -= states_covered

print(final_stations)

{'kone', 'kfive', 'ktwo', 'kthree'}


57. ДИНАМИЧЕСКОЕ ПРОГРАММИРОВАНИЕ - концепция, алгоритм который применяется для оптимизации какой-либо характеристики при заданных ограничениях. 
применяется в случаях, когда задача может быть разбита на втономные подзадачи.

Пример: задача о вещах которые нужно положить в рюкзак. Строится таблицы
Пример: задача на нахождение самой длинной общей подпоследовательности (человек вводит в поиск hish случайно и нужно предложить ему определение для слова fish)

ЛИНЕЙНОЕ ПРОГРАММИРОВАНИЕ используется для максимизации  некоторой характеристики при ограниченных условиях

58. АЛГОРИТМ k БЛИЖАЙШИХ СОСЕДЕЙ
Этот алгоритм применяется для КЛАССИФИКАЦИИ И РЕГРЕССИИ
Классификация - распределение по категориям
Регрессиия  - метод прогнозирования результата.
Применяется в машинном обучениии

59. ДЕРЕВЬЯ
Это как с бинарным поиском, спобос организации данных